[theme]

# -----------------
# 这是一个更专业、更柔和的“深蓝/石板灰”主题
# -----------------

# 主色调 (滑块、按钮等高亮颜色)
# 我们用一个冷静、专业的蓝色来替换掉刺眼的红色
primaryColor="#3B82F6"

# 主背景色 (替换掉纯黑)
# 这是一个非常深的蓝灰色，比纯黑更柔和
backgroundColor="#111827"

# 次级背景色 (侧边栏和图表块的背景)
# 这是一个比主背景稍亮的蓝灰色
secondaryBackgroundColor="#1F2937"

# 文本颜色 (替换掉纯白)
# 这是一个柔和的灰白色，降低对比度，眼睛更舒服
textColor="#E5E7EB"

# 字体
font="sans serif"
